train_seed: 0
n_networks: 10
layer_units: [50, 1]
layer_activations: ["relu", "linear"]
weight_prior_scale: 1
bias_prior_scale: 1
noise_var_prior_a: 0.5
noise_var_prior_b: 0.01
initial_unconstrained_scale: -1
transform_unconstrained_scale_factor: 0.5
learning_rate: 0.01
convergence_patience: 20
epochs: 100000
batch_size: 100